# -*- coding: utf-8 -*-
"""Alifya Mustafa Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A-oZbLEbTV-nvk4vKdXjTutwABbVfCkk

## Gemini
"""

pip install -q -U google-generativeai

import google.generativeai as genai
GOOGLE_API_KEY = 'AIzaSyBrHhDJQlt8oH-APRyyUBv_GbdZFvDM9-s'
genai.configure(api_key=GOOGLE_API_KEY)

for m in genai.list_models():
  if 'generateContent' in m.supported_generation_methods:
    print(m.name)

model = genai.GenerativeModel('gemini-pro')

response = model.generate_content("Describe a character who discovers an ancient map in their grandmother's attic, outlining the location of a hidden city believed to be a myth.")

import textwrap
from IPython.display import Markdown

def to_markdown(text):
  text = text.replace('•', '  *')
  return Markdown(textwrap.indent(text, '> ', predicate=lambda _: True))

to_markdown(response.text)

pip install --upgrade openai

response = model.generate_content("Describe an experience where a character visits an old, seemingly abandoned circus on the outskirts of their town during a foggy evening. Detail their initial apprehensions, the strange sights and sounds they encounter, and the mysterious performer who approaches them with a secretive smile.")

for chunk in response:
    print(chunk.text)

response = model.generate_content("Reflect on an experience where the character found a long-lost family heirloom. Describe why this discovery is important to them, how it has impacted their life, and what lessons they learned from this event.")

for chunk in response:
    print(chunk.text)

response = model.generate_content("After reflecting on the significance of discovering the long-lost family heirloom, the character begins to explore the history of the item. Delve into their journey as they uncover its origins, the ancestors connected to it, and the hidden secrets it holds. Describe how each revelation shapes their understanding of family, identity, and legacy.")

for chunk in response:
    print(chunk.text)

response = model.generate_content("After reflecting on the significance of discovering the long-lost family heirloom and exploring its history, the character writes a heartfelt message expressing their gratitude for the experience. Focus on the positive impact it has had on their understanding of family, identity, and legacy. Describe the deep emotions and new realizations, emphasizing how this journey has enriched their life and strengthened their connection to their ancestry.")

for chunk in response:
    print(chunk.text)

response = model.generate_content("Inspired by the revelations about the family heirloom and fueled by the emotions captured in their heartfelt gratitude message, the character decides to take action. They begin organizing a family reunion to share the story of the heirloom with relatives, many of whom are unaware of its existence and significance. Detail the preparations for the event, the anticipation, and the potential challenges they face in bringing together a dispersed family. Discuss how this event aims to reconnect the family and preserve their rich heritage for future generations.")

for chunk in response:
    print(chunk.text)

response = model.generate_content("As the family reunion comes to a close, the character reflects on the success of the event and the stronger bonds that have been forged among family members. They see relatives exchanging stories, laughter, and promises to keep in touch, realizing the immense value of their efforts. Sum up the story by describing the character’s final thoughts as they look at the heirloom one more time, now a symbol of their united family and a beacon of their shared history and future. Conclude with the character feeling a profound sense of fulfillment and hope for the future, knowing they have rekindled connections that will transcend generations.")

for chunk in response:
    print(chunk.text)

response = model.generate_content("The moral of the story is that understanding and embracing our heritage can lead to profound personal growth and stronger community bonds. The character's journey with the family heirloom not only deepened their own understanding of identity and history but also served as a catalyst for bringing together scattered family members. This story teaches us the importance of preserving our history, sharing our stories, and the powerful role that artifacts, like the heirloom, play in connecting generations. It highlights that in reconnecting with our past, we pave the way for a more united and meaningful future.")

for chunk in response:
    print(chunk.text)